name: validate-json-schema

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'data/students.json'  

  pull_request:
    paths:
      - 'data/students.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate JSON syntax
        run: |
          jq . data/students.json

  validate-schema:
    runs-on: ubuntu-latest
    needs: validate-json
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate JSON schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: 'data/schema.json'
          INPUT_JSONS: 'data/students.json'
