name: validate-json-schema

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - students
      - sample
    paths:
      - "data/students.json"

  pull_request:
    paths:
      - "data/students.json"

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate JSON syntax
        run: |
          jq . data/students.json

  validate-schema:
    runs-on: ubuntu-latest
    needs: validate-json
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
        
      - name: Install AJV Validator
        run: npm install -g ajv-cli ajv-formats
        
      - name: Validate JSON against Schema
        env:
          SCHEMA_PATH: data/schema.json
          DATA_PATH: data/students.json
        run: |
          ajv validate -s "$SCHEMA_PATH" -d "$DATA_PATH" --errors=text --spec=draft2020